title: SLS Info-Site
url: https://www.learning.moe.edu.sg
favicon: /images/Assets/apple-touch-icon.png
colors:
  primary-color: "#2b63d9"
  secondary-color: "#0b233f"
  media-colors:
    - title: media-color-one
      color: "#e96a6a"
    - title: media-color-two
      color: "#4ecbd3"
    - title: media-color-three
      color: "#fbbc04"
    - title: media-color-four
      color: "#ffffff"
    - title: media-color-five
      color: "#fbbc04"
description: The SLS is MOE's core platform for teaching and learning and is one
  of MOEâ€™s key initiatives to transform the learning experiences of Singaporean
  students through the purposeful use of technology to enable students to engage
  in different learning modes.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d19lt3odqxq3m6.amplifyapp.com
prod: https://master.d19lt3odqxq3m6.amplifyapp.com
shareicon: /images/LogoSecondaryLight.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: latest-post
